# Build workflow for the Femboy Clicker .NET project
name: Build Femboy Clicker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Ensure global.json is correct
    - name: Create global.json
      run: |
        echo '{
          "sdk": {
            "version": "6.0.400",
            "rollForward": "latestMinor"
          }
        }' > global.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    # Restore dependencies at the solution level if you have an .sln file
    - name: Restore Dependencies
      run: dotnet restore idkwhattoputhere.csproj

    # Build with platform specification
    - name: Build
      run: dotnet build idkwhattoputhere.csproj --configuration Release --no-restore --property:Platform=x86

    # Upload build artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Femboy-Clicker-Build
        path: |
          bin/Release/net6.0-windows/
          Assets/
